config/routes.rb
SampleApp::Application.routes.draw do

  resources :users
  root :to => 'pages#home'
  
  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  match '/signup', :to => 'users#new'
  
  get "pages/home"

  get "pages/contact"

  get "pages/about"
  
  get "pages/help"

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                 :integer          not null, primary key
#  name               :string(255)
#  email              :string(255)
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  encrypted_password :string(255)
#  salt               :string(255)
#

class User < ActiveRecord::Base
 
  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation# attr_accessible allows the name and email to be changed by the end-user, but not the id(because we obiviously do not want the user being able to change his/her user-id on our site)

  
  # As of now only doing a normal regex check. Need to be expanded to perform check using the Mail gem

  #Obtained the value of email regex from http://www.regular-expressions.info/email.html - does not work for some reason - troubleshooting regex is not a priority - using a different alternative

  #email_regex = /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i
  #email_regex = /(?:[a-z0-9!#$%&'*+\/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+\/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])/
  
  #Obtained this email_regexp from http://fightingforalostcause.net/misc/2006/compare-email-regex.php
  email_regex = /^(?!(?:(?:\x22?\x5C[\x00-\x7E]\x22?)|(?:\x22?[^\x5C\x22]\x22?)){255,})(?!(?:(?:\x22?\x5C[\x00-\x7E]\x22?)|(?:\x22?[^\x5C\x22]\x22?)){65,}@)(?:(?:[\x21\x23-\x27\x2A\x2B\x2D\x2F-\x39\x3D\x3F\x5E-\x7E]+)|(?:\x22(?:[\x01-\x08\x0B\x0C\x0E-\x1F\x21\x23-\x5B\x5D-\x7F]|(?:\x5C[\x00-\x7F]))*\x22))(?:\.(?:(?:[\x21\x23-\x27\x2A\x2B\x2D\x2F-\x39\x3D\x3F\x5E-\x7E]+)|(?:\x22(?:[\x01-\x08\x0B\x0C\x0E-\x1F\x21\x23-\x5B\x5D-\x7F]|(?:\x5C[\x00-\x7F]))*\x22)))*@(?:(?:(?!.*[^.]{64,})(?:(?:(?:xn--)?[a-z0-9]+(?:-[a-z0-9]+)*\.){1,126}){1,}(?:(?:[a-z][a-z0-9]*)|(?:(?:xn--)[a-z0-9]+))(?:-[a-z0-9]+)*)|(?:\[(?:(?:IPv6:(?:(?:[a-f0-9]{1,4}(?::[a-f0-9]{1,4}){7})|(?:(?!(?:.*[a-f0-9][:\]]){7,})(?:[a-f0-9]{1,4}(?::[a-f0-9]{1,4}){0,5})?::(?:[a-f0-9]{1,4}(?::[a-f0-9]{1,4}){0,5})?)))|(?:(?:IPv6:(?:(?:[a-f0-9]{1,4}(?::[a-f0-9]{1,4}){5}:)|(?:(?!(?:.*[a-f0-9]:){5,})(?:[a-f0-9]{1,4}(?::[a-f0-9]{1,4}){0,3})?::(?:[a-f0-9]{1,4}(?::[a-f0-9]{1,4}){0,3}:)?)))?(?:(?:25[0-5])|(?:2[0-4][0-9])|(?:1[0-9]{2})|(?:[1-9]?[0-9]))(?:\.(?:(?:25[0-5])|(?:2[0-4][0-9])|(?:1[0-9]{2})|(?:[1-9]?[0-9]))){3}))\]))$/i

  invalid_username_regex = /\A[[a-zA-z]\w+\s]+\z/
  validates         :name,  
                    presence: true,
                    format: { with: invalid_username_regex },
                    length: { maximum: 50 }
  validates         :email, 
                    presence: true,
                    format: { with: email_regex },
                    length: { maximum: 81 },
                    uniqueness: { case_sensitive: false }
  validates         :password,
                    presence: true,
                    confirmation: true,
                    length: {within: 6..80}

  before_save       :encrypt_password
  
  def has_password?(submitted_password)
    self.encrypted_password == encrypt(submitted_password)  
  end
 
  #self here refers to the user class i.e - User
  def self.authenticate(email, submitted_password)
    user = self.find_by_email(email)
    return nil if user.nil?
    return user if user.has_password?(submitted_password)
  end

  private
    def encrypt_password
      #self in this context refers to an object of the user class - i.e @user - an instance of the user class
      self.salt = make_salt if new_record?
      self.encrypted_password = encrypt(self.password)
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end
    
    def secure_hash (string)
      Digest::SHA2.hexdigest(string)
    end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end

  def contact
    @title = "Contact"
  end

  def about
    @title = "About"
  end
  
  def help
    @title = "Help"
  end

  def testing
    @title = "testing"
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
  	@user = User.find_by_id(params[:id])
        @title = @user.name 
  end
  
  def new
    @user = User.new
    @title = "Sign Up"
  end
  
  def create
    #raise params[:user].inspect
    @user = User.new(params[:user])
    if @user.save
      #Handle the successful save
      redirect_to user_path(@user), flash: {success: "Welcome to Sample App! - A micro Twitter attempt"}
    else
      @title = "Sign Up"
      render 'new'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def title
    base_title = "RoR Sample App"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end

  def logo
    image_tag("logo.png", alt: "Sample App", class: "round")
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = {size: 50,
                                    secure: false,
                                    rating: 'pg'} )
    gravatar_image_tag(user.email.downcase, 
                       alt: user.name, 
                       class: 'gravatar', 
                       gravatar: options)
  end
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
  <ul>
    <li><%= link_to "About", about_path %></li>
    <li><%= link_to "Contact", contact_path %></li>
    <li><%= link_to "PlanteRoRBlog", 'http://planetrubyonrails.com' %></li>
    <li><%= link_to "RailsOnTwitter", 'https://twitter.com/rails' %></li>
    <li><%= link_to "Blog", 'http://weblog.rubyonrails.org/' %></li>
  </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
      <header>
      <%= link_to logo, root_path%>
      <nav class="round">
        <ul>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <li><%= link_to "Sign In", '#' %></li>
        </ul>
        </nav>
      </header>

app/views/layouts/_stylesheets.html.erb
    <!--[if lt IE9]>
    <script src=http://htmlshiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <%= stylesheet_link_tag    "blueprint/screen", media: "screen, projection" %>
    <%= stylesheet_link_tag    "blueprint/print", media: "print" %>
    <!--[if lt IE8]><%stylesheet_link_tag "blueprint/ie", media: "all"%><![endif]-->
    <%= stylesheet_link_tag     "blueprint/custom",         media:"screen" %>
    <%= javascript_include_tag "application" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title><%= title %> </title>
    <%= csrf_meta_tags %>
    <%= render 'layouts/stylesheets' %>
  </head>
  <body>


    <div class="container"> 
      <%= render 'layouts/header'%>
      <section class="round">
        <% flash.each do |key, value| %>
          <div class="flash <%=key%>"> 
            <%= value %> 
          </div>
          <% end %>
        <%= yield %>
      </section>
      <%= render 'layouts/footer'%>

      <%= debug(params) if Rails.env.development?  %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Sample App</h1>
<p>Home page for Sample app based on RoR tutorial</p>

app/views/pages/contact.html.erb
<h1>Sample App</h1>
<p>Home page for Sample app based on RoR tutorial</p>

app/views/pages/help.html.erb
<h1>Sample App</h1>
<p>Home page for Sample app based on RoR tutorial</p>

app/views/pages/home.html.erb
<h1>Sample App</h1>
<p>Home page for Sample app based on RoR tutorial</p>
<p><a href = "http://www.cyogesh.com">My page</a></p>

<%= link_to "Sign up now!", signup_path, :class => "signup_button round" %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any?  %>
  <div id = "error_explaination">
    <h2>
      <%= pluralize(@user.errors.count, "error") %>
      prohibited this user from being saved:
    </h2>
    <p> There were problems with the following fields: </p>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
      <li> <%= message %> </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for(@user) do |f|  %>
  <%= render 'shared/error_messages'%>
  <div class = field>
    <%= f.label :name %><br />
    <%= f.text_field :name%><br />
    <%= f.label :email %><br />
    <%= f.email_field :email%><br />
    <%= f.label :password %><br />
    <%= f.password_field :password%><br />
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation%><br />
  </div>
  <div class = "actions">
    <%= f.submit "Sign Up" %><br />
  </div>

<% end %>

app/views/users/show.html.erb
<table class="profile", summary="profile information"> 
  <tr>
    <td class="main">

      <h1>
        <%= gravatar_for @user  %>
        <%= @user.name %> 
      </h1>
      
    </td>

    <td class="sidebar round">
      <strong>Name </strong><%= @user.name %> <br />
      <strong>URL </strong><%= link_to user_path(@user), @user %><br />
    </td>

  </tr>

</table>